### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by kunagpal** [IEEECS-VIT/motherload#1]
As of now, bower has not been properly excluded from the repository, as can be seen within public. Simply specifying the directory name in .gitignore is sufficient.

**Comment by BurnUalive** [comment]
It's added to .gitignore.

**Comment by BurnUalive** [comment]
Fixed. I was an error from a previous commit which I forgot to rectify.

**Comment by kunagpal** [comment]
Yes, specify directories with just a trailing slash, '/', no '*' needed at the end, that only works to specify all files of one particular extension.
