### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by BurnUalive** [IEEECS-VIT/motherload#4]
Finish it fast. Fix the following errors first.

1. The width of the li elements in the nav bar changes on hover.
2. The nav bar it self is not functioning properly.
3. When an image is clicked, a larger version of it is shown. The user is not able to exit from this view after clicking an image.

**Comment by TanishaChawla** [comment]
Sakshi is working on these errors.

**Comment by BurnUalive** [comment]
The display function takes too long to run. Optimize it.
